// Static site generator for Family Roofing Inc. — no dependencies.
// Usage: node build.mjs            -> writes the site to ./dist
//        FORM_ENDPOINT=https://… node build.mjs  -> override the quote form endpoint
import { rmSync, mkdirSync, cpSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { pages } from './src/pages.mjs';
import { SITE } from './src/data/site.mjs';
import { exactRedirects, PATTERN_REDIRECTS } from './src/data/redirects.mjs';

const OUT = 'dist';

rmSync(OUT, { recursive: true, force: true });
cpSync('src/static', OUT, { recursive: true });

const built = pages();
for (const page of built) {
  const file = page.path.endsWith('.html') ? join(OUT, page.path) : join(OUT, page.path, 'index.html');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, page.html);
}

// sitemap.xml — indexable pages only, absolute canonical URLs.
const today = new Date().toISOString().slice(0, 10);
const urls = built
  .filter((p) => !p.noindex)
  .map((p) => `  <url><loc>${SITE.url}${p.path}</loc><lastmod>${today}</lastmod><priority>${p.priority}</priority></url>`);
writeFileSync(join(OUT, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`);

// _redirects (Netlify / Cloudflare Pages): 301s from the old WordPress URLs.
// Each exact rule is written with and without the trailing slash, since hosts differ in
// whether they normalise it.
const pad = (s) => s.padEnd(60);
const exact = Object.entries(exactRedirects()).flatMap(([from, to]) => [
  `${pad(from)} ${to} 301`,
  `${pad(from.replace(/\/$/, ''))} ${to} 301`,
]);
const patterns = PATTERN_REDIRECTS.map(([from, to]) => `${pad(from)} ${to} 301`);
writeFileSync(join(OUT, '_redirects'), `# 301 redirects from the old WordPress site. GENERATED by build.mjs from
# src/data/redirects.mjs — edit that file, not this one.
${exact.join('\n')}
${patterns.join('\n')}
`);

// Preview builds (PREVIEW=1, e.g. the temporary workers.dev domain) must not be indexed:
// Google would see them as a duplicate of the real site.
if (process.env.PREVIEW) {
  writeFileSync(join(OUT, '_headers'), `/*
  X-Robots-Tag: noindex, nofollow
`);
}

writeFileSync(join(OUT, 'robots.txt'), `User-agent: *
Allow: /

Sitemap: ${SITE.url}/sitemap.xml
`);

writeFileSync(join(OUT, 'site.webmanifest'), JSON.stringify({
  name: SITE.name,
  short_name: 'Family Roofing',
  start_url: '/',
  display: 'browser',
  background_color: '#ffffff',
  theme_color: '#f8f0ce',
  icons: [
    { src: '/assets/img/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
    { src: '/assets/img/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    { src: '/assets/img/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/assets/img/icon-512.png', sizes: '512x512', type: 'image/png' },
  ],
}, null, 2));

console.log(`Built ${built.length} page(s) + sitemap.xml, robots.txt, _redirects (${exact.length / 2} old URLs + ${patterns.length} patterns) into ./${OUT}`);
